version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

    
    
  build:
    commands:
      - echo Maven Build ...
      - java -version
      - mvn clean package

       
artifacts:
     files:
      - '**/*'
     discard-paths: yes
     base-directory: target
     secondary-artifacts:
        1234:
           files: target/spring-boot.jar